common: &common
  keywords: "EZPad,code,collector,writing,translation"
  description: "code collector, article writing,translation writing"
  author: "Rique Li, hi@liwei.me"
  site_title: "EZPad -e development"
  content_type:  ["code collector", "translation", "writing", "copy and paste"]
  code_language: ["ruby", "python", "java", "c", "c++", "objective-c", "html", "css", "sql", "text", "yaml"]
  default_tags:  ["ruby", "rails", "rails3", "python", "java", "django", "email"]
  
development:
  <<: *common

test:
  <<: *common  

production:
  site_title: "EZPad, code collector for you."
